# Generated by Django 2.1.4 on 2018-12-23 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day_off', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPT', 'accept'), ('REJECT', 'reject'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('requested_user_note', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('LEADER', 'leader'), ('EMPLOYEE', 'employee')], default='EMPLOYEE', max_length=20)),
                ('available_day_off', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_requests', to='app.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.User'),
        ),
    ]
